name: 'Sync Upstream'

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch: 

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        ref:  main

    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
      with:
        target_sync_branch: main
        upstream_sync_repo: polito-WA-2026/materials
        upstream_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for errors
      if: failure()
      run: |
        echo "Si è verificato un errore durante la sincronizzazione."
        exit 1
